# Generated by Django 3.2.6 on 2021-10-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('PAUSED', 'PAUSED')], default='ACTIVE', max_length=10)),
            ],
        ),
    ]
